[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.1.1"

# Description
title = "Robotic Surgery Assets"
description="Extension containing configuration instances of different assets and sensors"
readme  = "docs/README.md"
repository = "https://github.com/isaac-for-healthcare/i4h-workflows"
category = "robotics"
keywords = ["robotics", "assets"]

[dependencies]

# Main python module this extension provides.
[[python.module]]
name = "robotic.surgery.assets"
