[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "Robotic Surgery Environments"
description="Extension containing suite of environments for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/isaac-for-healthcare/i4h-workflows"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"robotic.surgery.assets" = {}

# Main python module this extension provides.
[[python.module]]
name = "robotic.surgery.tasks"
