name: Copyright Check

on:
  pull_request:
    branches:
      - main

jobs:
  copyright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run copyright check
        run: |
          bash tools/check_missing_license.sh
