[project]
name = "ct-to-usd-converter"
version = "0.1.0"
description = "Medical CT data conversion tool for converting NRRD/NIfTI medical imaging files to USD format for use in IsaacSim and 3D visualization platforms"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "SimpleITK",
    "numpy",
    "vtk",
    "monai",
    "trimesh",
    "matplotlib",
    "usd-core",
    "nibabel",
    "itk",
    "scipy",
]

[tool.uv.sources]
ovlearn-dli-tools = { git = "ssh://git@gitlab-master.nvidia.com:12051/omni-robotics-learning/omniverse-learning-tools/ovlearn-dli-tools.git" }
